### ISSUE TITLE
[PkgEval] TaylorSeries may have a testing issue on Julia 0.4 (2015-01-30)

### ISSUE THREAD

**Issue by IainNZ** [lbenet/TaylorSeries.jl#2]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.4
* On **2015-01-29** the testing status was `Tests pass.`
* On **2015-01-30** the testing status changed to `Tests fail, but package loads.`

`Tests pass.` means that PackageEvaluator found the tests for your package, executed them, and they all passed.

`Tests fail, but package loads.` means that PackageEvaluator found the tests for your package, executed them, and they didn't pass. However, trying to load your package with `using` worked.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("TaylorSeries")' log
INFO: Installing TaylorSeries v0.0.1
INFO: Package database updated
INFO: METADATA is out-of-date a you may not have the latest version of TaylorSeries
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'using TaylorSeries' log

WARNING: deprecated syntax "{}" at /home/idunning/pkgtest/.julia/v0.4/TaylorSeries/src/TaylorSeries.jl:61.
Use "[]" instead.
Julia Version 0.4.0-dev+2997
Commit e41a507 (2015-01-30 05:35 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

>>> test log

WARNING: deprecated syntax "{}" at /home/idunning/pkgtest/.julia/v0.4/TaylorSeries/src/TaylorSeries.jl:61.
Use "[]" instead.

WARNING: itrunc(x) is deprecated, use trunc(Integer,x) instead.
 in depwarn at ./deprecated.jl:40
 in itrunc at deprecated.jl:29
 in ^ at /home/idunning/pkgtest/.julia/v0.4/TaylorSeries/src/utils_Taylor1.jl:207
 in anonymous at test.jl:87
 in do_test at test.jl:47
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:319
 in _start at ./client.jl:403
ERROR: LoadError: test failed: (2.718281828459045 == e = 2.7182818284590...)
 in expression: evalTaylor(exp(Taylor([0,1],17)),1.0) == e
 in error at error.jl:19
 in default_handler at test.jl:27
 in do_test at test.jl:50
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:319
 in _start at ./client.jl:403
while loading /home/idunning/pkgtest/.julia/v0.4/TaylorSeries/test/runtests.jl, in expression starting on line 69

INFO: Testing TaylorSeries
============================[ ERROR: TaylorSeries ]=============================

failed process: Process(`/home/idunning/julia04/usr/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/idunning/pkgtest/.julia/v0.4/TaylorSeries/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: TaylorSeries had test errors
 in error at error.jl:19
 in test at pkg/entry.jl:717
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:68
 in process_options at ./client.jl:241
 in _start at ./client.jl:403

>>> end of log
```

**Comment by lbenet** [comment]
Tests are passing again on my machine (with warnings due to `itrunc`, and others).

**Comment by IainNZ** [comment]
Great! PkgEval won't switch to `passing` until a new version is tagged.

**Comment by lbenet** [comment]
Thanks for the info; is there something else I can do without a new tag? I am planing to merge a branch which introduces lots of changes...
